language: python
python: '3.6'
notifications:
  email: false
sudo: enabled
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_b9cb4e99e0ea_key -iv $encrypted_b9cb4e99e0ea_iv
  -in iccu_rsa.enc -out /tmp/iccu_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- cd aws_lambda_function
- pip3 install -t . -r requirements.txt
- cd ..
script:
- ls
after_success:
- cd aws_lambda_function
- zip -r generator.zip *
- cd ..
- mkdir deploy-zip
- mv aws_lambda_function/generator.zip deploy-zip/
deploy:
  - provider: lambda
    function_name: generator
    region: eu-west-1
    role: arn:aws:iam::882482748234:role/lambda_basic_execution
    runtime: python3.6
    module_name: lambda
    handler_name: lambda_handler
    zip: deploy-zip/generator.zip
    secret_access_key:
      secure: bDz+2SN6Gvp2925Cz+3RiJ3koCOVj1IFAiHIDlEhXJYO622NJZyf9UlJLDSh/mQV5p1FLfV2VE6NWOfp0OQsJ/gJIzLugrwIV17GQBKZNT0ZxBCBPOED50qZdNFWUlpyPcv/3pnIX3munx8F83NPybjUQD6va0CJCR1FspgK7AWD2FbRHAeHtuDO013xFHBscjNleWx+MC2mEW7k9xnz0X7Feg4BaC0x87yM9AILTh/PRe1SrrM5qBewUAVTh+NvZaQ6+Ccxqie5wB7Vccr4bhumhioQ6JEOTDZzqY5wdKIXKHl4cR0Lr+Yop+FL6/VDBxNOPNj8u45UVTPOxGfBX2TXzTsKj0qD9giOSJ1TVW9pqR/BzKPrwu2SO2kWs645aR9/ZVD31jdaQ4LPQCtLbubHYkMnXs6vK0OxyxkH2JQjN/kNMFPmicrnfcfkbpl/jm+p/Zsrbx/emz039QzUDbgXtAqYJZH1fZJswDPbFEY2ufPMTPxLVHQK5RqJ5eq6fqx9MSslb0Wu6bFgHyAMm8fSpdaJy7UybLfDQFzIRGFVidSWIgrdbnbU7loYqykKBSECu4/j1P3FqflnUeoguYciFdtVhogYvikU4KygNpisApWXn9SN8e424fMrLJiOnJqLdQXL9GriZ7LhdERjvoiKOpia/sPovrtBup5db2A=
    access_key_id:
      secure: Ce1eFRJwvXCjJXRRoWd8lhl/YfzyeBxewBmn8lqCktjlirqVgCCc1vCS0rhvM9b2d02XCPRCexF3iGpxI6ZESiLPOoIW4WEG5efwjF7WItQw/3mg7pesCO3Y/RrNMIlNoDGNt6l7u/DOTICZsOIPIs30CjG7QAayHmxdul4VnxTtDpNNatYzO8kvQIJDNpplqXZQmJK8zs7r/ZwdJUw/ZnJOIn9IJcLglzBeCdyevLzYYGcSrwCv7Nns3gGrLdk+LKbwkP8WQA3rza6HV7+ETQMoypPlvDj9EVZT5I+Wsike34Yati9OLb72oxoUgvDmQplwPEsX08bMSlJpA/8D5Gm8mD4ytFUoAIHZa6qJmKjAgJ9bAJ/M5i9+OF/tCYW5oooYYtz1v6FRhtVawkJLiAjc44Irfe3p95JNKHS6BZEPsji9ksfYiAR7i6FbQXNGWf7m+xeU3GfDNBI2mT2hz2R5HvHaEYAZ2gssEUwMYP/4CKoCasWh6S6r0wa+WIPMX4BUjkbBKIv4YjFgxY1E4W+AjhHcAVkkwLAl376xrw91cZHqEXdd4bgW/od4m3jJeFqBgW5t7pHJxKiiCpcchaXAikFkuacNv4jkuA/pi5QTWq+8mlurAJ5Z4Dryd6RyaXpxCaasOfBALdXjjqld4yY8ijAqAQQKNf5PvXRMTfg=
  - provider: script
    script: git clone git@github.com:Imperial-CU/imperial-cu.github.io.git ; cp webpage/index.html imperial-cu.github.io/generator/index.html ; cd imperial-cu.github.io/ ; git add generator/index.html ; git commit -m "update newsletter generator" ; git push
